apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-nodejs
spec:
  type: NodePort
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
